### ISSUE TITLE
Bug in DoubleArrowSniff when maxPadding is not 1 but small enough

### ISSUE THREAD

**Issue by Xerkus** [webimpress/coding-standard#138]
with
```
    <rule ref="WebimpressCodingStandard.Arrays.DoubleArrow">
        <properties>
            <property name="maxPadding" value="2"/>
        </properties>
    </rule
```
I encounter following in a normal looking ConfigProvider:

> Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: str_repeat(): Second argument has to be greater than or equal to 0 in vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/Arrays/DoubleArrowSniff.php on line 217 in vendor/squizlabs/php_codesniffer/src/Runner.php:606
Stack trace:
#0 [internal function]: PHP_CodeSniffer\Runner->handleErrors()
#1 vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/Arrays/DoubleArrowSniff.php(217): str_repeat()
#2 vendor/webimpress/coding-standard/src/WebimpressCodingStandard/Sniffs/Arrays/DoubleArrowSniff.php(113): WebimpressCodingStandard\Sniffs\Arrays\DoubleArrowSniff->checkSpace()
#3 vendor/squizlabs/php_codesniffer/src/Sniffs/AbstractArraySniff.php(98): WebimpressCodingStandard\Sniffs\Arrays\DoubleArrowSniff->proce in vendor/squizlabs/php_codesniffer/src/Runner.php on line 606

In laminas coding standard we use value of 50, large enough that we never encounter this bug.

**Comment by michalbundyra** [comment]
@Xerkus 

> ... in a normal looking ConfigProvider

Can you provide an example please?

I just tried on one and it works for me, so I am not sure what is the "normal looking ConfigProvider". Thanks

**Comment by zigu007** [comment]
I have the same error.
I use `"laminas/laminas-coding-standard": "^2.1"` (`<rule ref="LaminasCodingStandard">`).
File example: [test.txt](https://github.com/webimpress/coding-standard/files/5754032/test.txt)

**Comment by Xerkus** [comment]
In my case it was `# obsolete comment format between lines`

**Comment by artemmolotov** [comment]
`webimpress/coding-standard:1.2.2`.

Same problem with the next class:
```
namespace App\Modules\Auth;

use App\Modules\Users as Users;
use League\OAuth2\Server\Repositories as LeagueOAuth2Repository;

final class ConfigProvider
{
    public function getDependencies(): array
    {
        return [
            'aliases' => [
                \Mezzio\Authentication\AuthenticationInterface::class => OAuth2\Adapter::class,

                LeagueOAuth2Repository\UserRepositoryInterface::class
                    => Users\Repository\Doctrine\UserRepository::class,

                OAuth2\Repository\AccessTokenRepository::class  => OAuth2\Repository\Dbal\AccessTokenRepository::class,
                OAuth2\Repository\RefreshTokenRepository::class => OAuth2\Repository\Dbal\RefreshTokenRepository::class,
            ],
        ];
    }
}

```
