### ISSUE TITLE
RedundantSemicolon.AfterScope for PHP 8 match expression

### ISSUE THREAD

**Issue by PatrickG** [webimpress/coding-standard#142]
```php
function (string $x): string {
    $y = match ($x) {
        'z' => 'Z',
        default => 'A',
    }; // <-- WebimpressCodingStandard.PHP.RedundantSemicolon.AfterScope

    return $y;
}
```

**Comment by michalbundyra** [comment]
@PatrickG thanks for reporting the issue. I've started investigating and find out that we have issue with `match` in many more sniffs, but also the main problem right now is that also PHP_CodeSniffer does not support that correctly. It's good enough now od dev-master, but still I've seen some one PRs to address match in other sniffs.

I can't really release the proper fix until we have released PHP_CodeSniffer 3.5.9, I'll keep my eyes on it.
