### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by xtreamwayz** [webimpress/coding-standard#3]
Hi webimpress,

any chance of creating a stable release? Without a stable release I can't release zend-coding-standard 2 without composer complaining or [adding extra dependencies](https://github.com/zendframework/zend-expressive-twigrenderer/pull/52/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R35).

**Comment by webimpress** [comment]
@xtreamwayz 

Sure, I am prioritising it for that week. There are still some small bits I want to finish here and then we should have first stable release!

**Comment by byan** [comment]
any update?

**Comment by webimpress** [comment]
Version [1.0.0](https://github.com/webimpress/coding-standard/releases/tag/1.0.0) released.
